wso2/carbon-event-processing

components/application-deployer/org.wso2.carbon.event.processing.application.deployer/src/main/java/org/wso2/carbon/event/processing/application/deployer/EventProcessingAppDeployerConstants.java
=> changing deployer types to cep/deployable_type to event-processing/deployable_type

components/event-processor/org.wso2.carbon.event.processor.core/pom.xml, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/EventProcessorDeployer.java, components/event-publisher/org.wso2.carbon.event.publisher.core/pom.xml, components/event-publisher/org.wso2.carbon.event.publisher.core/src/main/java/org/wso2/carbon/event/publisher/core/EventPublisherDeployer.java, components/event-receiver/org.wso2.carbon.event.receiver.core/pom.xml, components/event-receiver/org.wso2.carbon.event.receiver.core/src/main/java/org/wso2/carbon/event/receiver/core/EventReceiverDeployer.java, components/event-receiver/org.wso2.carbon.event.receiver.ui/src/main/resources/web/eventreceiver/js/create_eventReceiver_helper.js, features/event-simulator/org.wso2.carbon.event.simulator.server.feature/src/main/resources/conf/rdbms-configuration.xml, pom.xml
also resolving event stream, publisher, receiver and execution plan deploying issues
=> moving app deployer from event processing to analytics

components/event-simulator/org.wso2.carbon.event.simulator.core/src/main/java/org/wso2/carbon/event/simulator/core/EventSimulatorConstant.java
=> Resolving bug when sending an event with boolean attribute in event simulator

components/execution-manager/org.wso2.carbon.event.execution.manager.admin/src/main/java/org/wso2/carbon/event/execution/manager/admin/internal/util/DomainMapper.java, components/execution-manager/org.wso2.carbon.event.execution.manager.ui/src/main/resources/web/execution-manager/domain_configurations_ajaxprocessor.jsp, components/execution-manager/org.wso2.carbon.event.execution.manager.ui/src/main/resources/web/execution-manager/domains_ajaxprocessor.jsp, components/execution-manager/org.wso2.carbon.event.execution.manager.ui/src/main/resources/web/execution-manager/template_configurations_ajaxprocessor.jsp
Fixed JIRA : CEP-1153 - Execution Manager home page should show the t…emplate name and description
Fixed JIRA : CEP-1155 - Add favicon for new UI components Execution Manager
=> Fixed JIRAS : CEP-1153 and CEP-1155

components/event-processor/org.wso2.carbon.event.processor.ui/src/main/resources/web/eventprocessor/edit_execution_plan.jsp
https://wso2.org/jira/browse/CEP-1186
=> JIRA - CEP-1186 fixed

components/execution-manager/org.wso2.carbon.event.execution.manager.core/src/main/java/org/wso2/carbon/event/execution/manager/core/internal/CarbonExecutionManagerService.java, components/execution-manager/org.wso2.carbon.event.execution.manager.core/src/main/java/org/wso2/carbon/event/execution/manager/core/internal/util/ExecutionManagerHelper.java
[Execution Manager] Configurations created in super tenant are listed in tenant's Execution Manager UI
=> JIRA CEP-1211 fixed

components/event-processor/org.wso2.carbon.event.processor.common/pom.xml, components/event-processor/org.wso2.carbon.event.processor.storm/pom.xml, components/siddhi-tryit/org.wso2.carbon.siddhi.tryit.ui/pom.xml, features/event-processor/org.wso2.carbon.event.processor.server.feature/pom.xml, pom.xml
=> Disruptor updated to latest version 3.3.0

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/util/StormQueryPlanBuilder.java
=> Removing spaces form componenet name to avoid error when viweing the in storm UI

components/event-processor/org.wso2.carbon.event.processor.admin/src/main/java/org/wso2/carbon/event/processor/admin/EventProcessorAdminService.java, components/event-processor/org.wso2.carbon.event.processor.common/src/main/java/org/wso2/carbon/event/processor/common/util/AsyncEventPublisher.java, components/event-processor/org.wso2.carbon.event.processor.common/src/test/java/org/wso2/carbon/event/processor/storm/common/test/server/TCPEventSendingTestCase.java, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/manager/StormManagerServiceImpl.java
=> Handing connection failuers in Asynch Event publisher

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/SiddhiStormOutputEventListener.java, pom.xml
=> Adding manager ip and port when registering CEP publisher

components/event-processor/org.wso2.carbon.event.processor.common/src/main/java/org/wso2/carbon/event/processor/common/util/AsyncEventPublisher.java
=> Fixing https://wso2.org/jira/browse/CEP-1342

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/CarbonEventProcessorService.java
=> Fixing https://wso2.org/jira/browse/CEP-1349

components/event-processor/org.wso2.carbon.event.processor.core/src/test/java/org/wso2/event/processor/core/test/EventJunctionTestCase.java
=> Fixing test case

components/event-processor/org.wso2.carbon.event.processor.ui/src/main/resources/web/eventprocessor/js/annotation-hint.js, components/siddhi-tryit/org.wso2.carbon.siddhi.tryit.ui/src/main/resources/web/siddhitryit/js/annotation-hint.js
Added Annotation hints for `@From` and `@IndexBy`
=> Fix for https://wso2.org/jira/browse/CEP-1363

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/CarbonEventProcessorManagementService.java, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/CarbonEventProcessorService.java
Added HA-Persistence Implementation for CEP. Please review and merge.
=> HA-Persistence Implementation for CEP

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/StormTopologyManager.java
Fixed https://wso2.org/jira/browse/CEP-1403. Please review and merge.
=> Fixing https://wso2.org/jira/browse/CEP-1403

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/CarbonEventProcessorService.java, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/util/StormTopologyConstructor.java
Fixed https://wso2.org/jira/browse/CEP-1402. Please review and merge.
=> Fixed CEP-1402

features/event-throttler/org.wso2.carbon.event.throttler.feature/pom.xml, features/event-throttler/org.wso2.carbon.event.throttler.feature/src/main/resources/build.properties, features/event-throttler/org.wso2.carbon.event.throttler.feature/src/main/resources/conf/common_throttle_config.xml, features/event-throttler/org.wso2.carbon.event.throttler.feature/src/main/resources/conf/global-CEP-config.xml, features/event-throttler/org.wso2.carbon.event.throttler.feature/src/main/resources/p2.inf, pom.xml
=> Throttle development

components/event-processor/org.wso2.carbon.event.processor.core/pom.xml, pom.xml
Reverts wso2/carbon-event-processing#221
=> Revert "Added bumped versions"

pom.xml
Reverts wso2/carbon-event-processing#223
=> Revert "downgrading siddhi to 3.0.6-alpha"

components/event-processor/org.wso2.carbon.event.processor.ui/src/main/resources/web/eventprocessor/js/annotation-hint.js, components/event-processor/org.wso2.carbon.event.processor.ui/src/main/resources/web/eventprocessor/js/sql.js, components/siddhi-tryit/org.wso2.carbon.siddhi.tryit.ui/src/main/resources/web/siddhitryit/js/annotation-hint.js, components/siddhi-tryit/org.wso2.carbon.siddhi.tryit.ui/src/main/resources/web/siddhitryit/js/sql.js
Jira - [https://wso2.org/jira/browse/CEP-1465](url)
=> Adding missing keywords to the autocompletion

components/event-simulator/org.wso2.carbon.event.simulator.core/src/main/java/org/wso2/carbon/event/simulator/core/internal/CarbonEventSimulator.java
Jira - https://wso2.org/jira/browse/CEP-1534
=> Fixing event simulater field delimiter issue with regex metacharacters

features/geo-dashboard/org.wso2.carbon.geo.dashboard.feature/pom.xml
Corrected the licenced location
=> Corrected the licenced location

components/event-simulator/org.wso2.carbon.event.simulator.core/src/main/java/org/wso2/carbon/event/simulator/core/internal/CarbonEventSimulator.java
=> Changes according to the PR reviews

components/geo-dashboard/org.wso2.carbon.siddhi.geo.event.fuser/src/main/java/org/wso2/carbon/siddhi/geo/event/fuser/ExecutionPlanSubscriber.java, features/geo-dashboard/org.wso2.carbon.geo.dashboard.feature/src/main/capp/GadgetGeoDashboard_1.0.0/geo-dashboard/assets/html_templates/view_fence_popup.html, features/geo-dashboard/org.wso2.carbon.geo.dashboard.feature/src/main/capp/GadgetGeoDashboard_1.0.0/geo-dashboard/js/geo_fencing.js
Adding geo-fence popup view and fixing bug for subscribe function happened during constructing execution plan event flow
=> Adding fixes for geo-dashboard

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/util/EventProcessorUtil.java
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> improve xml parsing logic

components/event-simulator/org.wso2.carbon.event.simulator.ui/src/main/resources/web/eventsimulator/js/eventstreamProperty_load.js, components/event-simulator/org.wso2.carbon.event.simulator.ui/src/main/resources/web/eventsimulator/js/stream_configuration.js
- On Entering Event Stream Simulator page there is no Event Stream Name selected thus after getting list of propreties JS script throws Exception because of undefined fields
- Sending jsonData as QueryString parameter cause 400 (Bad Request) response - moved to form fields
=> CEVNTPROCE-1 issue fixed

components/event-processor/org.wso2.carbon.event.processor.common/src/main/java/org/wso2/carbon/event/processor/common/util/AsyncEventPublisher.java, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/SiddhiStormInputEventDispatcher.java, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/SiddhiStormOutputEventListener.java, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/manager/StormManagerServer.java, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/status/monitor/StormStatusMonitor.java
To name thread pools with better identification of threads
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Provided better namings for thread pools

pom.xml
Upgrade siddhi version to 3.2.0
Upgrade siddhi version to 3.2.0
Upgrade siddhi version to 3.2.0
NA
NA
NA
NA
NA
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
NA
NA
NA
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
NA
=> Upgrade siddhi version to 3.2.0

components/geo-dashboard/org.wso2.carbon.siddhi.geo.event.fuser/src/main/java/org/wso2/carbon/siddhi/geo/event/fuser/EventFusionProcessor.java
> When the execution plan count is 1, Fuse event processes the same streamEventChunk twice as per in https://github.com/wso2/carbon-event-processing/blob/3b35926b66db0f6abe35c626e5fa53392ca0d21d/components/geo-dashboard/org.wso2.carbon.siddhi.geo.event.fuser/src/main/java/org/wso2/carbon/siddhi/geo/event/fuser/EventFusionProcessor.java#L91 and https://github.com/wso2/carbon-event-processing/blob/3b35926b66db0f6abe35c626e5fa53392ca0d21d/components/geo-dashboard/org.wso2.carbon.siddhi.geo.event.fuser/src/main/java/org/wso2/carbon/siddhi/geo/event/fuser/EventFusionProcessor.java#L99.
This PR Resolves https://github.com/wso2/carbon-event-processing/issues/286
> N/A
> Removed invoking `nextProcessor.process(streamEventChunk)` twice.
> N/A
> Fixing event fusion processing the streamEventChunk …
=> Avoid processing streamEventChunk Twice

pom.xml
> Upgrade the following components dependency.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Upgrade the components dependency.

pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Fix the analytics common version.

pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Upgrading dependency versions.

components/event-simulator/org.wso2.carbon.event.simulator.core/src/main/java/org/wso2/carbon/event/simulator/core/internal/CarbonEventSimulator.java
Fix security issue of not closing sql Statement and Connection at the end of processing.
> Link(s) to product documentation …
=> Fix security issue

components/event-simulator/org.wso2.carbon.event.simulator.ui/src/main/resources/web/eventsimulator/index.jsp
> $subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Enable output encoding in event simulator file uploading feature

components/event-processor/org.wso2.carbon.event.processor.ui/src/main/resources/web/eventprocessor/validate_siddhi_queries_ajaxprocessor.jsp
=> Encode the printed message

components/event-flow/org.wso2.carbon.event.flow/pom.xml, components/event-flow/org.wso2.carbon.event.flow/src/main/java/org/wso2/carbon/event/flow/internal/EventFlowServiceDS.java, components/event-processor/org.wso2.carbon.event.processor.admin/pom.xml, components/event-processor/org.wso2.carbon.event.processor.admin/src/main/java/org/wso2/carbon/event/processor/admin/internal/ds/EventProcessorAdminServiceDS.java, components/event-processor/org.wso2.carbon.event.processor.common/pom.xml, components/event-processor/org.wso2.carbon.event.processor.core/pom.xml, components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/ds/EventProcessorServiceDS.java, components/event-processor/org.wso2.carbon.event.processor.siddhi.extension/pom.xml, components/event-processor/org.wso2.carbon.event.processor.siddhi.extension/src/main/java/org/wso2/carbon/event/processor/siddhi/extension/internal/SiddhiExtensionDS.java, components/event-processor/org.wso2.carbon.event.processor.template.deployer/pom.xml, components/event-processor/org.wso2.carbon.event.processor.template.deployer/src/main/java/org/wso2/carbon/event/processor/template/deployer/internal/ds/ExecutionPlanDeployerDS.java, components/event-simulator/org.wso2.carbon.event.simulator.admin/pom.xml, components/event-simulator/org.wso2.carbon.event.simulator.admin/src/main/java/org/wso2/carbon/event/simulator/admin/internal/ds/EventSimulatorAdminDS.java, components/event-simulator/org.wso2.carbon.event.simulator.core/pom.xml, components/event-simulator/org.wso2.carbon.event.simulator.core/src/main/java/org/wso2/carbon/event/simulator/core/internal/ds/EventSimulatorDS.java, components/siddhi-metrics/org.wso2.carbon.siddhi.metrics.core/pom.xml, components/siddhi-tryit/org.wso2.carbon.siddhi.tryit.ui/pom.xml, components/siddhi-tryit/org.wso2.carbon.siddhi.tryit.ui/src/main/java/org/wso2/carbon/siddhi/tryit/ui/internal/ds/SiddhiTryItServiceDS.java, pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Change new annotation and update version

pom.xml
update siddhi version to 3.2.5
=> update siddhi version to 3.2.5

features/event-flow/org.wso2.carbon.event.flow.server.feature/pom.xml, features/event-processor/org.wso2.carbon.event.processor.feature/pom.xml, features/event-processor/org.wso2.carbon.event.processor.server.feature/pom.xml, features/event-processor/org.wso2.carbon.event.processor.template.deployer.feature/pom.xml, features/event-processor/org.wso2.carbon.event.processor.ui.feature/pom.xml, features/event-simulator/org.wso2.carbon.event.simulator.feature/pom.xml, features/event-simulator/org.wso2.carbon.event.simulator.server.feature/pom.xml, features/event-simulator/org.wso2.carbon.event.simulator.ui.feature/pom.xml, features/siddhi-tryit/org.wso2.carbon.siddhi.tryit.feature/pom.xml, pom.xml
> Introduce new version property for the feature compatible version
=> Introduce new version property for the feature compatible version

pom.xml
update siddhi.version to 3.2.6
=> update siddhi.version to 3.2.6

pom.xml
Version upgrade for kernel release
=> Version upgrade for kernel release

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/storm/StormTopologyManager.java
> This PR fixes improper restriction of XXE
=> Fix improper restriction of XXE

components/event-processor/org.wso2.carbon.event.processor.core/src/main/java/org/wso2/carbon/event/processor/core/internal/CarbonEventProcessorService.java
Fix for https://github.com/wso2/product-apim/issues/7955
=> Fix state restoring in single node

components/event-processor/org.wso2.carbon.event.processor.ui/src/main/resources/web/eventprocessor/execution_plan_details.jsp
This PR adds subresource integrity checks to the third party script resource used in execution_plan_details.jsp
=> Fix subresource integrity for third party resource

pom.xml
Bump siddhi version from 3.2.7 to 3.2.8
=> Bump siddhi Version

pom.xml
Fixes https://github.com/wso2/api-manager/issues/1060
=> Bump Carbon.Analytics.Commons Version to 5.3.1

pom.xml
Upgrade following dependencies
guava -> 33.0.0-jre
snakeyaml -> 2.2
commons-lang3 -> 3.14.0
=> Upgrade snakeyaml to 2.2 and guava to 33.0.0

.github/workflows/coverage.yml
Build and upload code coverage statistics to codecov (https://app.codecov.io/)
=> Add coverage.yml git workflow

components/event-simulator/org.wso2.carbon.event.simulator.admin/src/main/java/org/wso2/carbon/event/simulator/admin/internal/util/EventSimulatorDataSourceInfo.java
> $subject related to a security enhancement
=> Close ResultSet

pom.xml
- Update commons-lang3 version
=> Update commons-lang3 Version
